Unifying `evm-block-recovery` CLI for automated runs
velas/velas-chain pull request #362
Opened 2022-09-21 09:39 UTC by Tirka

2022-09-21 13:49 UTC, gBaGu requested changes

2022-09-21 13:49 UTC, gBaGu commented on evm-utils/evm-block-recovery/src/routines/find.rs
> +    let mut total_limit = (end_block - start_block) as usize;
Handle the case when start_block > end_block

2022-09-21 13:49 UTC, gBaGu commented on evm-utils/evm-block-recovery/src/routines/find.rs
> +    }
I think line 35 will panic in case when there is no evm block with block_num=end_block

I'd suggest something like this:
```
        let next_range_start = start_block + limit as u64;
        if next_range_start < end_block {
            start_block = next_range_start;
            total_limit = (end_block - start_block) as usize;
            blocks.extend(chunk.iter());
            if let Some(&last_in_chunk) = chunk.last() {
                log::info!("Block #{last_in_chunk} loaded...");
            }
        } else {
            chunk.retain(|block| *block <= end_block);
            blocks.extend(chunk.iter());
            log::info!("All blocks loaded.");
            break;
        }
```

2022-09-21 13:49 UTC, gBaGu commented on evm-utils/evm-block-recovery/src/routines/find.rs
>          } else {
If this loop is the same for find_evm and find_native try moving it to separate function

2022-10-13 14:25 UTC, vldm commented
There a lot of questions related to the missing blocks at start and on end of range.
I have a patch that fixes incorrect ranges routine.  
[diff.txt](https://github.com/velas/velas-chain/files/9777620/diff.txt)

It also be nice to allow setting `--limit` in find(evm/native) commands - that would work in pair of end_block, but enchange user experience.

And also, for now it's some json status, which as regular CLI user is unexpected.
Please hide it under flag, and use cli status code insted (exit(0) -for success, exit(NotNull) for error).

2022-10-25 15:21 UTC, vldm approved these changes

2022-10-25 15:31 UTC, merged