Feat(cli): make evm-state path configurable
velas/velas-chain pull request #376
Opened 2022-10-10 08:39 UTC by gBaGu

2022-10-12 06:35 UTC, Tirka approved these changes

2022-10-18 12:22 UTC, vldm requested changes

2022-10-18 12:22 UTC, vldm commented on runtime/src/snapshot_utils.rs
> +pub(crate) const EVM_STATE_DIR: &str = "evm-state";
Use this const instead of default hardcoding in all place. 
You can move it to sdk if you have some linkage error.

2022-10-18 12:22 UTC, vldm commented on validator/src/main.rs
> +                .default_value("evm-state")
Default should be inside /ledger dir check `account_paths` argument for inspiration.


```rust
if let Ok(account_paths) = values_t!(matches, "account_paths", String) {
   ....
} else {
    vec![ledger_path.join("accounts")]
};
 ```
 
 
 (the same is true for rest tools)

2022-10-18 14:05 UTC, gBaGu commented on runtime/src/snapshot_utils.rs
> +pub(crate) const EVM_STATE_DIR: &str = "evm-state";
Done

2022-10-18 14:05 UTC, gBaGu commented on validator/src/main.rs
> +                .default_value("evm-state")
Done

2022-10-21 08:03 UTC, vldm approved these changes

2022-10-21 10:01 UTC, merged