Feature:(evm-subchains) Allocate `code`, `balance` and `nonce` as in `geth`
velas/velas-chain pull request #478
Opened 2024-10-25 16:03 UTC by Tirka

2024-10-28 10:22 UTC, vldm requested changes

2024-10-28 10:22 UTC, vldm commented on evm-utils/programs/evm_loader/src/lib.rs
> +        pub fn lamports_to_gwei<LAMPORTS: Into<U256>>(lamports: LAMPORTS) -> Gwei {
No, our lamports is always u64, so avoid generics

2024-10-28 10:22 UTC, vldm commented on evm-utils/programs/evm_loader/src/lib.rs
> +        pub fn lamports_to_gwei<LAMPORTS: Into<U256>>(lamports: LAMPORTS) -> Gwei {
But you can rename gwei to wei because of it miss-usage

2024-10-28 10:22 UTC, vldm commented on evm-utils/programs/evm_loader/src/processor.rs
> +                let AllocAccount {
this map should be simple .into()

2024-10-28 10:22 UTC, vldm commented on scripts/dev/bridge.nu
> +#!/usr/bin/env nu
nobody uses nushell,
please place `.gitignore` with `*` and use it locally

2024-10-28 10:22 UTC, vldm commented on evm-utils/programs/evm_loader/src/instructions/mod.rs
> +    pub fn new_with_balance<U: Into<U256>>(gwei: U) -> Self {
also avoid generics.
u64 for `lamports` aka nano VLX
and  u256 is for `weis` aka atto VLX, generics make it easy to use it incorrectly.

2024-10-28 17:53 UTC, Tirka commented on evm-utils/programs/evm_loader/src/processor.rs
> +                let AllocAccount {
Resolved

2024-10-28 17:54 UTC, Tirka commented on scripts/dev/bridge.nu
> +#!/usr/bin/env nu
😭😭😭

2024-10-28 17:54 UTC, Tirka commented on evm-utils/programs/evm_loader/src/instructions/mod.rs
> +    pub fn new_with_balance<U: Into<U256>>(gwei: U) -> Self {
Resolved

2024-11-03 11:33 UTC, vldm approved these changes

2024-11-03 17:00 UTC, merged